### ISSUE TITLE
Ability to record Meeting minutes and task management

### ISSUE THREAD

**Issue by virtualit786** [faysal-ahmad/idreesia-erp#12]
There should be a module that allows recording the meeting minutes of a meeting by different committees. Meeting minute items can be simple text summaries and also can be tasks that can be assigned to different committee members or karkuns. There should be a tasks tab under a karkun details view. Tasks progress would also need to be recorded. There should also be a global tasks view that would show tasks of different committees and members.

**Comment by faysal-ahmad** [comment]
Not needed.
